import React, { useState, useEffect } from 'react';
import '../styles/global.scss';
import Head from 'next/head';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';
import { AppWrapper } from '../utils/context/state';
function MyApp({ Component, pageProps }) {
  const [refresh, setRefresh] = useState(false);

  useEffect(() => {
    console.log('refreshed');
  }, [refresh]);

  return (
    <AppWrapper>
      <Head>
        <title>Influence | Find your influence</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='appContainer'>
        <Component {...pageProps} />
        <Footer />
      </main>
    </AppWrapper>
  );
}

export default MyApp;
