import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Influence | Find your influence</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Find your creative link. Clink up.</div>
    </div>
  );
}
